# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlNt6SOE60PWb5QtQyi6DVcSd7c62bQT
"""

import torch

# Check if GPU is avaiālable
if torch.cuda.is_available():
    print("GPU is available!")
    print("Device name:", torch.cuda.get_device_name(0))
else:
    print("GPU is NOT available.")

from google.colab import drive
drive.mount('/content/drive')

!pip install torch torchvision torchaudio
!pip install matplotlib
!pip install tqdm

!ls "/content/drive/MyDrive/"

from google.colab import drive
drive.mount('/content/drive')

!ls -l "/content/drive/MyDrive/"

!ls "/content/drive/MyDrive/hackthon"

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/hackthon"
!ls

import os

# Create main working folder
os.makedirs("/content/hackathon", exist_ok=True)

print("Main hackathon folder created!")

!pip install torch torchvision
!pip install segmentation-models-pytorch albumentations opencv-python

!ls /content/hackathon

!ls /content/hackathon/Offroad_Segmentation_Scripts

!ls -R /content/hackathon

import zipfile
import os

# Create folder if not exists
os.makedirs("/content/hackathon", exist_ok=True)

zip_files = [
    "/content/drive/MyDrive/hackthon/Offroad_Segmentation_Scripts.zip",
    "/content/drive/MyDrive/hackthon/Offroad_Segmentation_Training_Dataset.zip",
    "/content/drive/MyDrive/hackthon/Offroad_Segmentation_testImages.zip"
]

for zip_path in zip_files:
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall("/content/hackathon")

print("✅ All files extracted successfully!")

!ls -R /content/hackathon

!ls /content/hackathon

file_path = "/content/hackathon/train_segmentation.py"

with open(file_path, "r") as f:
    content = f.read()

content = content.replace(
    "os.path.join(script_dir, '..', 'Offroad_Segmentation_Training_Dataset', 'train')",
    "os.path.join(script_dir, 'Offroad_Segmentation_Training_Dataset', 'train')"
)

content = content.replace(
    "os.path.join(script_dir, '..', 'Offroad_Segmentation_Training_Dataset', 'val')",
    "os.path.join(script_dir, 'Offroad_Segmentation_Training_Dataset', 'val')"
)

with open(file_path, "w") as f:
    f.write(content)

print("✅ Dataset path fixed correctly!")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/hackathon
!python train_segmentation.py

